export const installed_blueprints = [
  //@BlueprintInsertion
{ name: 'UserProfile38426', human_name: 'User Profile', access_route: 'UserProfile38426'},
{ name: 'Tutorial38425', human_name: 'Tutorial', access_route: 'Tutorial38425', icon: 'question-circle'},
{ name: 'NotificationList38397', human_name: 'Notification List', access_route: 'NotificationList38397'},
{ name: 'Settings38396', human_name: 'Settings', access_route: 'Settings38396'},
{ name: 'Settings38388', human_name: 'Settings', access_route: 'Settings38388'},
{ name: 'UserProfile38386', human_name: 'User Profile', access_route: 'UserProfile38386'},
{ name: 'UserProfile38355', human_name: 'User Profile', access_route: 'UserProfile38355'},
{ name: 'Tutorial38354', human_name: 'Tutorial', access_route: 'Tutorial38354', icon: 'question-circle'},
{ name: 'NotificationList38326', human_name: 'Notification List', access_route: 'NotificationList38326'},
{ name: 'Settings38325', human_name: 'Settings', access_route: 'Settings38325'},
{ name: 'Settings38317', human_name: 'Settings', access_route: 'Settings38317'},
{ name: 'UserProfile38315', human_name: 'User Profile', access_route: 'UserProfile38315'},
{ name: 'ArticleList38277', human_name: 'Article List', access_route: 'ArticleList38277'},
{ name: 'ArticleList38276', human_name: 'Article List', access_route: 'ArticleList38276'},
{ name: 'ArticleList38275', human_name: 'Article List', access_route: 'ArticleList38275'},
{ name: 'UserProfile38265', human_name: 'User Profile', access_route: 'UserProfile38265'},
{ name: 'Tutorial38264', human_name: 'Tutorial', access_route: 'Tutorial38264', icon: 'question-circle'},
{ name: 'NotificationList38236', human_name: 'Notification List', access_route: 'NotificationList38236'},
{ name: 'Settings38235', human_name: 'Settings', access_route: 'Settings38235'},
{ name: 'Settings38227', human_name: 'Settings', access_route: 'Settings38227'},
{ name: 'UserProfile38225', human_name: 'User Profile', access_route: 'UserProfile38225'},
{ name: 'ArticleList38187', human_name: 'Article List', access_route: 'ArticleList38187'},
{ name: 'ArticleList38186', human_name: 'Article List', access_route: 'ArticleList38186'},
{ name: 'ArticleList38185', human_name: 'Article List', access_route: 'ArticleList38185'},
{ name: 'ArticleList38168', human_name: 'Article List', access_route: 'ArticleList38168'},
{ name: 'ArticleList38167', human_name: 'Article List', access_route: 'ArticleList38167'},
{ name: 'ArticleList38166', human_name: 'Article List', access_route: 'ArticleList38166'},
{ name: 'ArticleList38134', human_name: 'Article List', access_route: 'ArticleList38134'},
{ name: 'ArticleList38133', human_name: 'Article List', access_route: 'ArticleList38133'},
{ name: 'ArticleList38132', human_name: 'Article List', access_route: 'ArticleList38132'},
{ name: 'Messenger', human_name: 'Messenger', access_route: 'Messenger', icon: 'comments'},
{ name: 'Tutorial', human_name: 'Tutorial', access_route: 'Tutorial', icon: 'question-circle'},
{ name: 'Maps', human_name: 'Maps', access_route: 'Maps', icon: 'map'},
{ name: 'Calendar', human_name: 'Calendar', access_route: 'Calendar', icon: 'calendar'},
{ name: 'Camera', human_name: 'Camera', access_route: 'Camera', icon: 'camera'},
{ name: 'EmailAuth', human_name: 'EmailAuth', access_route: 'EmailAuth', icon: 'envelope-o'},

  // you can add more installed blueprints here
  // access route is the route nate given to navigator
];
